#!/bin/bash
#PBS -N 20170714_ccpVTZ_ccsdt_chloroflourobutane
#PBS -l nodes=1:ppn=8
#PBS -l walltime=8:00:00
#PBS -l pmem=2000mb
#PBS -e /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201705_butane/201705_transitionState/201706_CCSDT/20170714_ccpVTZ_ccsdt_chloroflourobutane.err
#PBS -o /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201705_butane/201705_transitionState/201706_CCSDT/20170714_ccpVTZ_ccsdt_chloroflourobutane.log
#PBS -q mesabi

module load python

# create scratch directory
scratch=/scratch.global/graha682/201706_CCSDT/20170714_ccpVTZ_ccsdt_chloroflourobutane
if [[ -d $scratch ]]; then
    i=0
    while [[ -d $scratch-$i ]]; do
        let i++
    done
    scratch=$scratch-$i
fi
rm -rf $scratch 2> /dev/null
mkdir -p $scratch
cd $scratch

python /home/goodpast/shared/repositories/pyscf_wrapper/run_pySCF.py /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201705_butane/201705_transitionState/201706_CCSDT/20170714_ccpVTZ_ccsdt_chloroflourobutane.inp > /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201705_butane/201705_transitionState/201706_CCSDT/20170714_ccpVTZ_ccsdt_chloroflourobutane.out

cd ${PBS_O_WORKDIR}
rm -rf $scratch 2> /dev/null
