#!/bin/bash -l
#
# Job: 201707_augccpVTZ_m06_pentacene
#
#
# qg09 version 1.0.10
#
# To submit this script to the queue type:
#    qsub 201707_augccpVTZ_m06_pentacene.pbs
#
#PBS -m n
#PBS -l nodes=1:ppn=24
#PBS -l walltime=5:00:00
#PBS -l mem=60000mb
#PBS -e 201707_augccpVTZ_m06_pentacene.e
#PBS -o 201707_augccpVTZ_m06_pentacene.o
#PBS -q mesabi
#

cd $PBS_O_WORKDIR

ulimit -s unlimited

cd /home/goodpast/graha682/201705_pentaceneRxn/201705_singleMolecule/201705_reactant/201707_M06
mkdir -p /scratch/$USER/$PBS_JOBID  
export GAUSS_SCRDIR=/scratch/$USER/$PBS_JOBID  
module load gaussian/g09.e01  
fix_input 201707_augccpVTZ_m06_pentacene.com  
/usr/bin/time g09 < 201707_augccpVTZ_m06_pentacene.com >& 201707_augccpVTZ_m06_pentacene.out  
rm /scratch/$USER/$PBS_JOBID/*.rwf  

