#!/bin/bash -l
#
# Job: 201707_ccpVDZ_m06_12Hpentacene
#
#
# qg09 version 1.0.10
#
# To submit this script to the queue type:
#    qsub 201707_ccpVDZ_m06_12Hpentacene.pbs
#
#PBS -m n
#PBS -l nodes=1:ppn=8
#PBS -l walltime=5:00:00
#PBS -l mem=12000mb
#PBS -e 201707_ccpVDZ_m06_12Hpentacene.e
#PBS -o 201707_ccpVDZ_m06_12Hpentacene.o
#PBS -q batch
#

cd $PBS_O_WORKDIR

ulimit -s unlimited

cd /home/goodpast/graha682/201705_pentaceneRxn/201705_singleMolecule/201705_product/201705_M06
mkdir -p /scratch/$USER/$PBS_JOBID  
export GAUSS_SCRDIR=/scratch/$USER/$PBS_JOBID  
module load gaussian/g09.d01_itasca  
fix_input 201707_ccpVDZ_m06_12Hpentacene.com  
/usr/bin/time g09 < 201707_ccpVDZ_m06_12Hpentacene.com >& 201707_ccpVDZ_m06_12Hpentacene.out  
rm /scratch/$USER/$PBS_JOBID/*.rwf  

