#!/bin/bash
#PBS -N 20170717_321g_m06_ccsdt_ft_3pentacene
#PBS -l nodes=1:ppn=8
#PBS -l walltime=12:00:00
#PBS -l pmem=2500mb
#PBS -e /panfs/roc/groups/13/goodpast/graha682/201705_pentaceneRxn/201705_singleMolecule/201705_reactant/201705_freezeAndThaw/20170717_321g_m06_ccsdt_ft_3pentacene.err
#PBS -o /panfs/roc/groups/13/goodpast/graha682/201705_pentaceneRxn/201705_singleMolecule/201705_reactant/201705_freezeAndThaw/20170717_321g_m06_ccsdt_ft_3pentacene.log
#PBS -q mesabi

module load python

# create scratch directory
scratch=/scratch.global/graha682/201705_freezeAndThaw/20170717_321g_m06_ccsdt_ft_3pentacene
if [[ -d $scratch ]]; then
    i=0
    while [[ -d $scratch-$i ]]; do
        let i++
    done
    scratch=$scratch-$i
fi
rm -rf $scratch 2> /dev/null
mkdir -p $scratch
cd $scratch

python /home/goodpast/graha682/code/python/freeze_and_thaw/cython/cmain.py /panfs/roc/groups/13/goodpast/graha682/201705_pentaceneRxn/201705_singleMolecule/201705_reactant/201705_freezeAndThaw/20170717_321g_m06_ccsdt_ft_3pentacene.inp > /panfs/roc/groups/13/goodpast/graha682/201705_pentaceneRxn/201705_singleMolecule/201705_reactant/201705_freezeAndThaw/20170717_321g_m06_ccsdt_ft_3pentacene.out

cd ${PBS_O_WORKDIR}
rm -rf $scratch 2> /dev/null
