#!/bin/bash -l
#
# Job: 20171117_ccpVTZ_hs_m06_hexaaquaFe
#
#
# qg09 version 1.0.10
#
# To submit this script to the queue type:
#    qsub 20171117_ccpVTZ_hs_m06_hexaaquaFe.pbs
#
#PBS -m n
#PBS -l nodes=1:ppn=24
#PBS -l walltime=5:00:00
#PBS -l mem=60000mb
#PBS -e 20171117_ccpVTZ_hs_m06_hexaaquaFe.e
#PBS -o 20171117_ccpVTZ_hs_m06_hexaaquaFe.o
#PBS -q mesabi
#

cd $PBS_O_WORKDIR

ulimit -s unlimited

cd /home/goodpast/graha682/201711_hexaaquaFe/201711_optimizedStructures
mkdir -p /scratch/$USER/$PBS_JOBID  
export GAUSS_SCRDIR=/scratch/$USER/$PBS_JOBID  
module load gaussian/g09.e01  
fix_input 20171117_ccpVTZ_hs_m06_hexaaquaFe.com  
/usr/bin/time g09 < 20171117_ccpVTZ_hs_m06_hexaaquaFe.com >& 20171117_ccpVTZ_hs_m06_hexaaquaFe.out  
rm /scratch/$USER/$PBS_JOBID/*.rwf  

