#!/bin/bash
#PBS -N 20170714_ccpVTZ_m06_ccsdt_ft_4chlorohexane
#PBS -l nodes=1:ppn=16
#PBS -l walltime=24:00:00
#PBS -l pmem=2000mb
#PBS -e /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201705_hexane/201705_reactant/201707_freezeAndThaw/201801_wfcycle/20170714_ccpVTZ_m06_ccsdt_ft_4chlorohexane.err
#PBS -o /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201705_hexane/201705_reactant/201707_freezeAndThaw/201801_wfcycle/20170714_ccpVTZ_m06_ccsdt_ft_4chlorohexane.log
#PBS -q mesabi

module load python

# create scratch directory
scratch=/scratch.global/graha682/201801_wfcycle/20170714_ccpVTZ_m06_ccsdt_ft_4chlorohexane
if [[ -d $scratch ]]; then
    i=0
    while [[ -d $scratch-$i ]]; do
        let i++
    done
    scratch=$scratch-$i
fi
rm -rf $scratch 2> /dev/null
mkdir -p $scratch
cd $scratch

python /home/goodpast/graha682/code/python/freeze_and_thaw/cython/cmain.py /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201705_hexane/201705_reactant/201707_freezeAndThaw/201801_wfcycle/20170714_ccpVTZ_m06_ccsdt_ft_4chlorohexane.inp > /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201705_hexane/201705_reactant/201707_freezeAndThaw/201801_wfcycle/20170714_ccpVTZ_m06_ccsdt_ft_4chlorohexane.out

cd ${PBS_O_WORKDIR}
rm -rf $scratch 2> /dev/null
