#!/bin/bash
#PBS -N 201711_ccpVDZ_NEVPT2_0c12h24_local
#PBS -l nodes=1:ppn=16
#PBS -l walltime=02:00:00
#PBS -l pmem=30000mb
#PBS -e /panfs/roc/groups/13/goodpast/graha682/201711_twistCAS/201712_midTwist/201712_NEVPT2/D0/CAS_MOD/201711_ccpVDZ_NEVPT2_0c12h24_local.err
#PBS -o /panfs/roc/groups/13/goodpast/graha682/201711_twistCAS/201712_midTwist/201712_NEVPT2/D0/CAS_MOD/201711_ccpVDZ_NEVPT2_0c12h24_local.log
#PBS -q ram1t

module load python
# create scratch directory
scratch=/scratch.global/graha682/201711_ccpVDZ_NEVPT2_0c12h24_local
if [[ -d $scratch ]]; then
    i=0
    while [[ -d $scratch-$i ]]; do
        let i++
    done
    scratch=$scratch-$i
fi
rm -rf $scratch 2> /dev/null
mkdir -p $scratch
cd $scratch

python /home/goodpast/graha682/code/python/scripts/pyscf_wrapper/run_pySCF.py /panfs/roc/groups/13/goodpast/graha682/201711_twistCAS/201712_midTwist/201712_NEVPT2/D0/CAS_MOD/201711_ccpVDZ_NEVPT2_0c12h24_local.inp > /panfs/roc/groups/13/goodpast/graha682/201711_twistCAS/201712_midTwist/201712_NEVPT2/D0/CAS_MOD/201711_ccpVDZ_NEVPT2_0c12h24_local.out

cd ${PBS_O_WORKDIR}
rm -rf $scratch 2> /dev/null
