#!/bin/bash
#PBS -N mof5_node_ah2
#PBS -l nodes=1:ppn=32
#PBS -l walltime=96:00:00
#PBS -l pmem=31000mb
#PBS -e /panfs/roc/groups/13/goodpast/graha682/201706_MOF5/201802_FT/mof5_node_ah2.err
#PBS -o /panfs/roc/groups/13/goodpast/graha682/201706_MOF5/201802_FT/mof5_node_ah2.log
#PBS -q ram1t

module load python
# create scratch directory
scratch=/scratch.global/graha682/mof5_node_ah2
if [[ -d $scratch ]]; then
    i=0
    while [[ -d $scratch-$i ]]; do
        let i++
    done
    scratch=$scratch-$i
fi
rm -rf $scratch 2> /dev/null
mkdir -p $scratch
cd $scratch

python /home/goodpast/graha682/code/python/freeze_and_thaw/cython/cmain.py /panfs/roc/groups/13/goodpast/graha682/201706_MOF5/201802_FT/mof5_node_ah2.inp > /panfs/roc/groups/13/goodpast/graha682/201706_MOF5/201802_FT/mof5_node_ah2.out

cd ${PBS_O_WORKDIR}
rm -rf $scratch 2> /dev/null
