#!/bin/bash
#PBS -N 20170816_augccpVDZ_m06_ccsdt_ft_6flourooctane135triene_p
#PBS -l nodes=1:ppn=8
#PBS -l walltime=8:00:00
#PBS -l pmem=2000mb
#PBS -e /panfs/roc/groups/13/goodpast/graha682/201706_flTrieneElim/201706_octane/201706_reactant/201707_freezeAndThaw/diff_den/20170816_augccpVDZ_m06_ccsdt_ft_6flourooctane135triene_p.err
#PBS -o /panfs/roc/groups/13/goodpast/graha682/201706_flTrieneElim/201706_octane/201706_reactant/201707_freezeAndThaw/diff_den/20170816_augccpVDZ_m06_ccsdt_ft_6flourooctane135triene_p.log
#PBS -q mesabi

module load python

# create scratch directory
scratch=/scratch.global/graha682/diff_den/20170816_augccpVDZ_m06_ccsdt_ft_6flourooctane135triene_p
if [[ -d $scratch ]]; then
    i=0
    while [[ -d $scratch-$i ]]; do
        let i++
    done
    scratch=$scratch-$i
fi
rm -rf $scratch 2> /dev/null
mkdir -p $scratch
cd $scratch

python /home/goodpast/graha682/code/python/freeze_and_thaw/cython/cmain.py /panfs/roc/groups/13/goodpast/graha682/201706_flTrieneElim/201706_octane/201706_reactant/201707_freezeAndThaw/diff_den/20170816_augccpVDZ_m06_ccsdt_ft_6flourooctane135triene_p.inp > /panfs/roc/groups/13/goodpast/graha682/201706_flTrieneElim/201706_octane/201706_reactant/201707_freezeAndThaw/diff_den/20170816_augccpVDZ_m06_ccsdt_ft_6flourooctane135triene_p.out

cd ${PBS_O_WORKDIR}
rm -rf $scratch 2> /dev/null
