#!/bin/bash
#PBS -N 201711_ccpVDZ_NEVPT2_90c12h24
#PBS -l nodes=1:ppn=8
#PBS -l walltime=04:00:00
#PBS -l pmem=2000mb
#PBS -e /panfs/roc/groups/13/goodpast/graha682/201711_twistCAS/201712_midTwist/201712_NEVPT2/D90/201711_ccpVDZ_NEVPT2_90c12h24.err
#PBS -o /panfs/roc/groups/13/goodpast/graha682/201711_twistCAS/201712_midTwist/201712_NEVPT2/D90/201711_ccpVDZ_NEVPT2_90c12h24.log
#PBS -q mesabi

module load python

# create scratch directory
scratch=/scratch.global/graha682/D90/201711_ccpVDZ_NEVPT2_90c12h24
if [[ -d $scratch ]]; then
    i=0
    while [[ -d $scratch-$i ]]; do
        let i++
    done
    scratch=$scratch-$i
fi
rm -rf $scratch 2> /dev/null
mkdir -p $scratch
cd $scratch

python /home/goodpast/graha682/code/python/scripts/pyscf_wrapper/run_pySCF.py /panfs/roc/groups/13/goodpast/graha682/201711_twistCAS/201712_midTwist/201712_NEVPT2/D90/201711_ccpVDZ_NEVPT2_90c12h24.inp > /panfs/roc/groups/13/goodpast/graha682/201711_twistCAS/201712_midTwist/201712_NEVPT2/D90/201711_ccpVDZ_NEVPT2_90c12h24.out

cd ${PBS_O_WORKDIR}
rm -rf $scratch 2> /dev/null
