#!/bin/bash
#PBS -N 20180109_ccpVDZ_m06_ccsdt_ft_1chloroflourobutane
#PBS -l nodes=1:ppn=16
#PBS -l walltime=2:00:00
#PBS -l pmem=2000mb
#PBS -e /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201705_butane/201705_transitionState/201705_freezeAndThaw/201801_wfcycle/20180109_ccpVDZ_m06_ccsdt_ft_1chloroflourobutane.err
#PBS -o /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201705_butane/201705_transitionState/201705_freezeAndThaw/201801_wfcycle/20180109_ccpVDZ_m06_ccsdt_ft_1chloroflourobutane.log
#PBS -q mesabi

module load python

# create scratch directory
scratch=/scratch.global/graha682/201801_wfcycle/20180109_ccpVDZ_m06_ccsdt_ft_1chloroflourobutane
if [[ -d $scratch ]]; then
    i=0
    while [[ -d $scratch-$i ]]; do
        let i++
    done
    scratch=$scratch-$i
fi
rm -rf $scratch 2> /dev/null
mkdir -p $scratch
cd $scratch

python /home/goodpast/graha682/code/python/freeze_and_thaw/cython/cmain.py /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201705_butane/201705_transitionState/201705_freezeAndThaw/201801_wfcycle/20180109_ccpVDZ_m06_ccsdt_ft_1chloroflourobutane.inp > /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201705_butane/201705_transitionState/201705_freezeAndThaw/201801_wfcycle/20180109_ccpVDZ_m06_ccsdt_ft_1chloroflourobutane.out

cd ${PBS_O_WORKDIR}
rm -rf $scratch 2> /dev/null
