#!/bin/bash

FILENOEXT=$( echo $1 | cut -d \. -f 1)
FILENAME=$1

export FILENOEXT

perl -pi -e 's/#PBS -N .*/#PBS -N $ENV{FILENOEXT}/' $2 

export FILENAME

perl -pi -e 's/###INPUT_FILE_NAME###/$ENV{FILENAME}/' $2


if [ -z "$3" ]
  then
    JOBSUBMIT="cat $2"
else
    JOBSUBMIT="qsub -q $3 $2"
fi

for i in {1..10}; do
 JOBID=$( eval $JOBSUBMIT | cut -d \. -f 1)
 CHECKJOB=eval "qstat $JOBID"
 while [[ $CHECKJOB != *"Uknown Job Id"* ]]; do
  sleep 5m
 done
done

echo Done
