#!/bin/bash
#PBS -N 201709_ccpVDZ_m062x_flourine
#PBS -l nodes=1:ppn=8
#PBS -l walltime=01:00:00
#PBS -l pmem=2000mb
#PBS -e /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201709_flourine/201709_ccpVDZ_m062x_flourine.err
#PBS -o /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201709_flourine/201709_ccpVDZ_m062x_flourine.log
#PBS -q mesabi

module load python

# create scratch directory
scratch=/scratch.global/graha682/201709_flourine/201709_ccpVDZ_m062x_flourine
if [[ -d $scratch ]]; then
    i=0
    while [[ -d $scratch-$i ]]; do
        let i++
    done
    scratch=$scratch-$i
fi
rm -rf $scratch 2> /dev/null
mkdir -p $scratch
cd $scratch

python /home/goodpast/shared/repositories/pyscf_wrapper/run_pySCF.py /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201709_flourine/201709_ccpVDZ_m062x_flourine.inp > /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201709_flourine/201709_ccpVDZ_m062x_flourine.out

cd ${PBS_O_WORKDIR}
rm -rf $scratch 2> /dev/null
