#!/bin/bash
#PBS -N 20170712_ccpVDZ_m06_ccsdt_ft_2chloropentane
#PBS -l nodes=1:ppn=8
#PBS -l walltime=01:00:00
#PBS -l pmem=2000mb
#PBS -e /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201705_pentane/201705_reactant/201707_freezeAndThaw/201804_density/20170712_ccpVDZ_m06_ccsdt_ft_2chloropentane.err
#PBS -o /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201705_pentane/201705_reactant/201707_freezeAndThaw/201804_density/20170712_ccpVDZ_m06_ccsdt_ft_2chloropentane.log
#PBS -q mesabi

module load python

# create scratch directory
scratch=/scratch.global/graha682/20170712_ccpVDZ_m06_ccsdt_ft_2chloropentane
if [[ -d $scratch ]]; then
    i=0
    while [[ -d $scratch-$i ]]; do
        let i++
    done
    scratch=$scratch-$i
fi
rm -rf $scratch 2> /dev/null
mkdir -p $scratch
cd $scratch

python /home/goodpast/graha682/code/python/freeze_and_thaw/cython/cmain.py /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201705_pentane/201705_reactant/201707_freezeAndThaw/201804_density/20170712_ccpVDZ_m06_ccsdt_ft_2chloropentane.inp > /panfs/roc/groups/13/goodpast/graha682/201705_sn2Rxn/201705_pentane/201705_reactant/201707_freezeAndThaw/201804_density/20170712_ccpVDZ_m06_ccsdt_ft_2chloropentane.out

cd ${PBS_O_WORKDIR}
rm -rf $scratch 2> /dev/null
