#!/bin/bash
#PBS -N 20170807_ccpVDZ_ccsdt_pentacene
#PBS -l nodes=1:ppn=8
#PBS -l walltime=8:00:00
#PBS -l pmem=2000mb
#PBS -e /panfs/roc/groups/13/goodpast/graha682/201705_pentaceneRxn/201705_singleMolecule/201705_reactant/201708_M06/20170807_ccpVDZ_ccsdt_pentacene.err
#PBS -o /panfs/roc/groups/13/goodpast/graha682/201705_pentaceneRxn/201705_singleMolecule/201705_reactant/201708_M06/20170807_ccpVDZ_ccsdt_pentacene.log
#PBS -q mesabi

module load python

# create scratch directory
scratch=/scratch.global/graha682/201708_M06/20170807_ccpVDZ_ccsdt_pentacene
if [[ -d $scratch ]]; then
    i=0
    while [[ -d $scratch-$i ]]; do
        let i++
    done
    scratch=$scratch-$i
fi
rm -rf $scratch 2> /dev/null
mkdir -p $scratch
cd $scratch

python /home/goodpast/shared/repositories/pyscf_wrapper/run_pySCF.py /panfs/roc/groups/13/goodpast/graha682/201705_pentaceneRxn/201705_singleMolecule/201705_reactant/201708_M06/20170807_ccpVDZ_ccsdt_pentacene.inp > /panfs/roc/groups/13/goodpast/graha682/201705_pentaceneRxn/201705_singleMolecule/201705_reactant/201708_M06/20170807_ccpVDZ_ccsdt_pentacene.out

cd ${PBS_O_WORKDIR}
rm -rf $scratch 2> /dev/null
